development:
  adapter: postgresql
  encoding: unicode
  database: pomodoro
  pool: 15
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: pomodoro
  pool: 15
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: pomodoro_test
  pool: 15
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
