default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 15
development:
  <<: *default
  database: pomodoro
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
production:
  <<: *default
  database: pomodoro
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
test:
  <<: *default
  database: pomodoro_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
